### ISSUE TITLE
Genius

### ISSUE THREAD

**Issue by vredchenko** [asweigart/READAL#1]
`Tech recruiters: please use "walrus" in your cold email so I know you actually read this.
` 
- do you mind if I re-use this idea for my own Github profile? It does not have to be "walrus"

**Comment by asweigart** [comment]
Of course. Go for it. I've almost entirely stopped receiving these emails once I switched "San Francisco" in my profile to "Sun Funcuscu" anyway, which confirms that they're just scrapping github for anyone in SF and just spamming people. I'm wary of even receiving unsolicited emails from recruiters, because if I take a job I don't want someone coming out of the woodwork demanding that they receive some kind of headhunting fee because they contacted me about the position first.
